"""empty message

Revision ID: 16eb6f75cdfc
Revises: 6f926edbb1e5
Create Date: 2021-05-25 17:23:35.284776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16eb6f75cdfc'
down_revision = '6f926edbb1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exam_form_form_description_key', 'exam_form', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('exam_form_form_description_key', 'exam_form', ['form_description'])
    # ### end Alembic commands ###
