"""empty message

Revision ID: 5397530c5895
Revises: c3c05bb3b3d4
Create Date: 2021-08-10 20:04:46.338522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5397530c5895'
down_revision = 'c3c05bb3b3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'admin_id')
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
