"""empty message

Revision ID: 5458147d6773
Revises: f8e21b50e2f1
Create Date: 2021-05-21 21:30:50.507694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5458147d6773'
down_revision = 'f8e21b50e2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_user', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_user', 'details')
    # ### end Alembic commands ###
