"""empty message

Revision ID: 6f926edbb1e5
Revises: 5458147d6773
Create Date: 2021-05-24 14:58:12.472218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f926edbb1e5'
down_revision = '5458147d6773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('examinee_id', sa.Integer(), nullable=True),
    sa.Column('exam_form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_form_id'], ['exam_form.id'], ),
    sa.ForeignKeyConstraint(['examinee_id'], ['session_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_response')
    # ### end Alembic commands ###
