"""empty message

Revision ID: 79201f0ce145
Revises: 
Create Date: 2021-05-31 21:22:45.185455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79201f0ce145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('proctor_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctor_session_name'), 'proctor_session', ['name'], unique=True)
    op.create_table('exam_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_description', sa.JSON(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('proctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proctor_id'], ['proctor_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id_card', sa.String(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('proctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proctor_id'], ['proctor_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('examinee_id', sa.Integer(), nullable=True),
    sa.Column('exam_form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_form_id'], ['exam_form.id'], ),
    sa.ForeignKeyConstraint(['examinee_id'], ['session_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_response')
    op.drop_table('session_user')
    op.drop_table('exam_form')
    op.drop_index(op.f('ix_proctor_session_name'), table_name='proctor_session')
    op.drop_table('proctor_session')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
