"""empty message

Revision ID: a45fd351e0ed
Revises: fc0451d6eb36
Create Date: 2021-04-21 00:40:12.911866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45fd351e0ed'
down_revision = 'fc0451d6eb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proctor_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctor_session_name'), 'proctor_session', ['name'], unique=True)
    op.create_table('session_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('proctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proctor_id'], ['proctor_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_user')
    op.drop_index(op.f('ix_proctor_session_name'), table_name='proctor_session')
    op.drop_table('proctor_session')
    # ### end Alembic commands ###
