"""empty message

Revision ID: b1545d308e60
Revises: a45fd351e0ed
Create Date: 2021-04-22 18:01:46.087423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1545d308e60'
down_revision = 'a45fd351e0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proctor_session', sa.Column('parent_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proctor_session', 'user', ['parent_user_id'], ['id'])
    op.create_unique_constraint(None, 'session_user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_user', type_='unique')
    op.drop_constraint(None, 'proctor_session', type_='foreignkey')
    op.drop_column('proctor_session', 'parent_user_id')
    # ### end Alembic commands ###
