"""empty message

Revision ID: c388939858d5
Revises: cf1e52bf5c8d
Create Date: 2021-05-10 21:53:10.981580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c388939858d5'
down_revision = 'cf1e52bf5c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_user', sa.Column('id_card', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_user', 'id_card')
    # ### end Alembic commands ###
