"""empty message

Revision ID: cf1e52bf5c8d
Revises: b1545d308e60
Create Date: 2021-05-06 19:21:45.109543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1e52bf5c8d'
down_revision = 'b1545d308e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_user_name_key', 'session_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('session_user_name_key', 'session_user', ['name'])
    # ### end Alembic commands ###
